// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configedit} from '../models';
import {theme} from '../models';
import {uiprefs} from '../models';

export function BrowseOpen():Promise<configedit.StateDTO>;

export function BrowseSaveAs():Promise<string>;

export function BrowseScriptFile():Promise<string>;

export function ChangeSecretsPIN(arg1:string,arg2:string,arg3:configedit.ConfigDTO):Promise<configedit.ConfigDTO>;

export function ClearRecentConfigs():Promise<Array<string>>;

export function CreateSecretsPIN(arg1:string):Promise<configedit.SecretsDTO>;

export function DataFolderPath():Promise<string>;

export function DeleteTheme(arg1:string):Promise<void>;

export function GetDefaultMessages(arg1:string):Promise<Record<string, any>>;

export function GetEditableMessages(arg1:string):Promise<Record<string, any>>;

export function GetMessages():Promise<Record<string, any>>;

export function GetTheme():Promise<theme.State>;

export function GetUIPrefs():Promise<uiprefs.Prefs>;

export function InitialState():Promise<configedit.StateDTO>;

export function KnownTerminals():Promise<Array<string>>;

export function LockSecrets():Promise<void>;

export function LockValue(arg1:string):Promise<string>;

export function NewBlank():Promise<configedit.StateDTO>;

export function OpenDataFolder():Promise<void>;

export function OpenInEditor():Promise<void>;

export function OpenRecent(arg1:string):Promise<configedit.StateDTO>;

export function PreviewAction(arg1:configedit.ItemDTO,arg2:Array<configedit.FieldDTO>,arg3:configedit.ActionDTO):Promise<configedit.ActionPreviewDTO>;

export function PreviewItem(arg1:configedit.ItemDTO,arg2:Array<configedit.FieldDTO>,arg3:Array<configedit.DisplayDTO>,arg4:string):Promise<configedit.PreviewDTO>;

export function PreviewScriptFile(arg1:string):Promise<configedit.ScriptPreviewDTO>;

export function RecentConfigs():Promise<Array<string>>;

export function RemoveSecretsPIN(arg1:string,arg2:configedit.ConfigDTO):Promise<configedit.ConfigDTO>;

export function RevealValue(arg1:string):Promise<string>;

export function Save(arg1:configedit.ConfigDTO,arg2:string):Promise<configedit.SaveResultDTO>;

export function SaveMessages(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SaveTheme(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function SecretsState(arg1:configedit.SecretsDTO):Promise<configedit.SecretsStateDTO>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUIFonts(arg1:string,arg2:string):Promise<uiprefs.Prefs>;

export function SetUIScale(arg1:number):Promise<uiprefs.Prefs>;

export function UnlockSecrets(arg1:string,arg2:configedit.SecretsDTO):Promise<void>;

export function ValidateConfig(arg1:configedit.ConfigDTO):Promise<Array<configedit.ValidationIssueDTO>>;

export function ValidateField(arg1:string,arg2:string):Promise<string>;
