// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseOpen() {
  return window['go']['configedit']['App']['BrowseOpen']();
}

export function BrowseSaveAs() {
  return window['go']['configedit']['App']['BrowseSaveAs']();
}

export function GetDefaultMessages(arg1) {
  return window['go']['configedit']['App']['GetDefaultMessages'](arg1);
}

export function GetEditableMessages(arg1) {
  return window['go']['configedit']['App']['GetEditableMessages'](arg1);
}

export function GetMessages() {
  return window['go']['configedit']['App']['GetMessages']();
}

export function InitialState() {
  return window['go']['configedit']['App']['InitialState']();
}

export function KnownTerminals() {
  return window['go']['configedit']['App']['KnownTerminals']();
}

export function NewBlank() {
  return window['go']['configedit']['App']['NewBlank']();
}

export function PreviewAction(arg1, arg2, arg3) {
  return window['go']['configedit']['App']['PreviewAction'](arg1, arg2, arg3);
}

export function PreviewItem(arg1, arg2, arg3, arg4) {
  return window['go']['configedit']['App']['PreviewItem'](arg1, arg2, arg3, arg4);
}

export function Save(arg1, arg2) {
  return window['go']['configedit']['App']['Save'](arg1, arg2);
}

export function SaveMessages(arg1, arg2) {
  return window['go']['configedit']['App']['SaveMessages'](arg1, arg2);
}

export function SetDefaultMessages(arg1) {
  return window['go']['configedit']['App']['SetDefaultMessages'](arg1);
}

export function ValidateConfig(arg1) {
  return window['go']['configedit']['App']['ValidateConfig'](arg1);
}

export function ValidateField(arg1, arg2) {
  return window['go']['configedit']['App']['ValidateField'](arg1, arg2);
}
