// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function BrowseConfig():Promise<string>;

export function CancelInlineAction(arg1:number,arg2:number):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetActionDetail(arg1:number,arg2:number):Promise<gui.ActionDetailDTO>;

export function GetActionGroups():Promise<Array<gui.ActionGroupDTO>>;

export function GetActions(arg1:number):Promise<Array<gui.ActionDTO>>;

export function GetInlineStatus(arg1:number,arg2:number):Promise<gui.InlineStatusDTO>;

export function GetItemDetails(arg1:number):Promise<gui.DetailsDTO>;

export function GetItems():Promise<Array<gui.ItemDTO>>;

export function GetMessages():Promise<Record<string, any>>;

export function GetTheme():Promise<string>;

export function LaunchConfigEditor():Promise<boolean>;

export function LoadError():Promise<string>;

export function ReloadConfig():Promise<string>;

export function RunAction(arg1:number,arg2:number):Promise<void>;

export function RunActionInline(arg1:number,arg2:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
