// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseConfig() {
  return window['go']['gui']['App']['BrowseConfig']();
}

export function CancelInlineAction(arg1, arg2) {
  return window['go']['gui']['App']['CancelInlineAction'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['gui']['App']['CopyToClipboard'](arg1);
}

export function GetActionDetail(arg1, arg2) {
  return window['go']['gui']['App']['GetActionDetail'](arg1, arg2);
}

export function GetActionGroups() {
  return window['go']['gui']['App']['GetActionGroups']();
}

export function GetActions(arg1) {
  return window['go']['gui']['App']['GetActions'](arg1);
}

export function GetInlineStatus(arg1, arg2) {
  return window['go']['gui']['App']['GetInlineStatus'](arg1, arg2);
}

export function GetItemDetails(arg1) {
  return window['go']['gui']['App']['GetItemDetails'](arg1);
}

export function GetItems() {
  return window['go']['gui']['App']['GetItems']();
}

export function GetMessages() {
  return window['go']['gui']['App']['GetMessages']();
}

export function GetTitles() {
  return window['go']['gui']['App']['GetTitles']();
}

export function LaunchConfigEditor() {
  return window['go']['gui']['App']['LaunchConfigEditor']();
}

export function LoadError() {
  return window['go']['gui']['App']['LoadError']();
}

export function ReloadConfig() {
  return window['go']['gui']['App']['ReloadConfig']();
}

export function RunAction(arg1, arg2) {
  return window['go']['gui']['App']['RunAction'](arg1, arg2);
}

export function RunActionInline(arg1, arg2) {
  return window['go']['gui']['App']['RunActionInline'](arg1, arg2);
}

export function SetDefaultMessages(arg1) {
  return window['go']['gui']['App']['SetDefaultMessages'](arg1);
}
