// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionNeedsUnlock(arg1, arg2) {
  return window['go']['gui']['App']['ActionNeedsUnlock'](arg1, arg2);
}

export function BrowseConfig() {
  return window['go']['gui']['App']['BrowseConfig']();
}

export function CancelInlineAction(arg1, arg2) {
  return window['go']['gui']['App']['CancelInlineAction'](arg1, arg2);
}

export function ClearRecentConfigs() {
  return window['go']['gui']['App']['ClearRecentConfigs']();
}

export function CopyToClipboard(arg1) {
  return window['go']['gui']['App']['CopyToClipboard'](arg1);
}

export function GetActionDetail(arg1, arg2) {
  return window['go']['gui']['App']['GetActionDetail'](arg1, arg2);
}

export function GetActionGroups() {
  return window['go']['gui']['App']['GetActionGroups']();
}

export function GetActions(arg1) {
  return window['go']['gui']['App']['GetActions'](arg1);
}

export function GetInlineStatus(arg1, arg2) {
  return window['go']['gui']['App']['GetInlineStatus'](arg1, arg2);
}

export function GetItemDetails(arg1) {
  return window['go']['gui']['App']['GetItemDetails'](arg1);
}

export function GetItems() {
  return window['go']['gui']['App']['GetItems']();
}

export function GetMessages() {
  return window['go']['gui']['App']['GetMessages']();
}

export function GetTheme() {
  return window['go']['gui']['App']['GetTheme']();
}

export function GetUIPrefs() {
  return window['go']['gui']['App']['GetUIPrefs']();
}

export function GetVersion() {
  return window['go']['gui']['App']['GetVersion']();
}

export function LaunchConfigEditor() {
  return window['go']['gui']['App']['LaunchConfigEditor']();
}

export function LoadError() {
  return window['go']['gui']['App']['LoadError']();
}

export function LoadRecentConfig(arg1) {
  return window['go']['gui']['App']['LoadRecentConfig'](arg1);
}

export function LockSecrets() {
  return window['go']['gui']['App']['LockSecrets']();
}

export function Log(arg1) {
  return window['go']['gui']['App']['Log'](arg1);
}

export function LogPath() {
  return window['go']['gui']['App']['LogPath']();
}

export function OpenScriptInEditor(arg1) {
  return window['go']['gui']['App']['OpenScriptInEditor'](arg1);
}

export function RecentConfigs() {
  return window['go']['gui']['App']['RecentConfigs']();
}

export function ReloadConfig() {
  return window['go']['gui']['App']['ReloadConfig']();
}

export function RunAction(arg1, arg2) {
  return window['go']['gui']['App']['RunAction'](arg1, arg2);
}

export function RunActionInline(arg1, arg2) {
  return window['go']['gui']['App']['RunActionInline'](arg1, arg2);
}

export function SecretsState() {
  return window['go']['gui']['App']['SecretsState']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['gui']['App']['SetAlwaysOnTop'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['gui']['App']['SetTheme'](arg1);
}

export function SetUIScale(arg1) {
  return window['go']['gui']['App']['SetUIScale'](arg1);
}

export function SetWindowOpacity(arg1) {
  return window['go']['gui']['App']['SetWindowOpacity'](arg1);
}

export function UnlockSecrets(arg1) {
  return window['go']['gui']['App']['UnlockSecrets'](arg1);
}

export function WatchScript(arg1) {
  return window['go']['gui']['App']['WatchScript'](arg1);
}
