// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {theme} from '../models';
import {uiprefs} from '../models';

export function ActionNeedsUnlock(arg1:number,arg2:number):Promise<boolean>;

export function BrowseConfig():Promise<string>;

export function CancelInlineAction(arg1:number,arg2:number):Promise<void>;

export function ClearRecentConfigs():Promise<Array<string>>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetActionDetail(arg1:number,arg2:number):Promise<gui.ActionDetailDTO>;

export function GetActionGroups():Promise<Array<gui.ActionGroupDTO>>;

export function GetActions(arg1:number):Promise<Array<gui.ActionDTO>>;

export function GetInlineStatus(arg1:number,arg2:number):Promise<gui.InlineStatusDTO>;

export function GetItemDetails(arg1:number):Promise<gui.DetailsDTO>;

export function GetItems():Promise<Array<gui.ItemDTO>>;

export function GetMessages():Promise<Record<string, any>>;

export function GetTheme():Promise<theme.State>;

export function GetUIPrefs():Promise<uiprefs.Prefs>;

export function GetVersion():Promise<Record<string, string>>;

export function LaunchConfigEditor():Promise<boolean>;

export function LoadError():Promise<string>;

export function LoadRecentConfig(arg1:string):Promise<void>;

export function LockSecrets():Promise<void>;

export function Log(arg1:string):Promise<void>;

export function LogPath():Promise<string>;

export function OpenScriptInEditor(arg1:string):Promise<void>;

export function RecentConfigs():Promise<Array<string>>;

export function ReloadConfig():Promise<string>;

export function RunAction(arg1:number,arg2:number):Promise<void>;

export function RunActionInline(arg1:number,arg2:number):Promise<void>;

export function SecretsState():Promise<gui.SecretsStateDTO>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUIScale(arg1:number):Promise<uiprefs.Prefs>;

export function SetWindowOpacity(arg1:number):Promise<void>;

export function UnlockSecrets(arg1:string):Promise<void>;

export function WatchScript(arg1:string):Promise<void>;
