// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetActionDetail(arg1:number,arg2:number):Promise<gui.ActionDetailDTO>;

export function GetActions(arg1:number):Promise<Array<gui.ActionDTO>>;

export function GetItemDetails(arg1:number):Promise<gui.DetailsDTO>;

export function GetItems():Promise<Array<gui.ItemDTO>>;

export function GetTitles():Promise<gui.TitlesDTO>;

export function ReloadConfig():Promise<void>;

export function RunAction(arg1:number,arg2:number):Promise<void>;
