// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetActionDetail(arg1, arg2) {
  return window['go']['main']['App']['GetActionDetail'](arg1, arg2);
}

export function GetActions(arg1) {
  return window['go']['main']['App']['GetActions'](arg1);
}

export function GetItemDetails(arg1) {
  return window['go']['main']['App']['GetItemDetails'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetTitles() {
  return window['go']['main']['App']['GetTitles']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}
