// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetActionDetail(arg1:number,arg2:number):Promise<main.ActionDetailDTO>;

export function GetActions(arg1:number):Promise<Array<main.ActionDTO>>;

export function GetItemDetails(arg1:number):Promise<main.DetailsDTO>;

export function GetItems():Promise<Array<main.ItemDTO>>;

export function GetTitles():Promise<main.TitlesDTO>;

export function ReloadConfig():Promise<void>;

export function RunAction(arg1:number,arg2:number):Promise<void>;
